<a href="https://colab.research.google.com/github/VipulR2796/premier_league_results_prediction/blob/main/ML_Data_Cleaning_Premier_League_Stats.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing required libraries

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pylab as plt
from matplotlib import pyplot

In [6]:
epl_data = pd.read_csv("https://raw.githubusercontent.com/VipulR2796/premier_league_results_prediction/main/df_full_premierleague.csv")

In [ ]:
epl_data.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4070 entries, 0 to 4069
Data columns (total 114 columns):
 #    Column                    Dtype
---   ------                    -----
 0    Unnamed: 0                int64
 1    link_match                object
 2    season                    object
 3    date                      object
 4    home_team                 object
 5    away_team                 object
 6    result_full               object
 7    result_ht                 object
 8    home_clearances           float64
 9    home_corners              float64
 10   home_fouls_conceded       float64
 11   home_offsides             float64
 12   home_passes               float64
 13   home_possession           float64
 14   home_red_cards            float64
 15   home_shots                float64
 16   home_shots_on_target      float64
 17   home_tackles              float64
 18   home_touches              float64
 19   home_yellow_cards         float64
 20   away_clearances           float64
 21   away_corners              float64
 22   away_fouls_conceded       float64
 23   away_offsides             float64
 24   away_passes               float64
 25   away_possession           float64
 26   away_red_cards            float64
 27   away_shots                float64
 28   away_shots_on_target      float64
 29   away_tackles              float64
 30   away_touches              float64
 31   away_yellow_cards         float64
 32   goal_home_ft              int64
 33   goal_away_ft              int64
 34   sg_match_ft               int64
 35   goal_home_ht              int64
 36   goal_away_ht              int64
 37   sg_match_ht               int64
 38   clearances_avg_H          float64
 39   corners_avg_H             float64
 40   fouls_conceded_avg_H      float64
 41   offsides_avg_H            float64
 42   passes_avg_H              float64
 43   possession_avg_H          float64
 44   red_cards_avg_H           float64
 45   shots_avg_H               float64
 46   shots_on_target_avg_H     float64
 47   tackles_avg_H             float64
 48   touches_avg_H             float64
 49   yellow_cards_avg_H        float64
 50   goals_scored_ft_avg_H     float64
 51   goals_conced_ft_avg_H     float64
 52   sg_match_ft_acum_H        float64
 53   goals_scored_ht_avg_H     float64
 54   goals_conced_ht_avg_H     float64
 55   sg_match_ht_acum_H        float64
 56   performance_acum_H        float64
 57   clearances_avg_A          float64
 58   corners_avg_A             float64
 59   fouls_conceded_avg_A      float64
 60   offsides_avg_A            float64
 61   passes_avg_A              float64
 62   possession_avg_A          float64
 63   red_cards_avg_A           float64
 64   shots_avg_A               float64
 65   shots_on_target_avg_A     float64
 66   tackles_avg_A             float64
 67   touches_avg_A             float64
 68   yellow_cards_avg_A        float64
 69   goals_scored_ft_avg_A     float64
 70   goals_conced_ft_avg_A     float64
 71   sg_match_ft_acum_A        float64
 72   goals_scored_ht_avg_A     float64
 73   goals_conced_ht_avg_A     float64
 74   sg_match_ht_acum_A        float64
 75   performance_acum_A        float64
 76   clearances_avg_home       float64
 77   corners_avg_home          float64
 78   fouls_conceded_avg_home   float64
 79   offsides_avg_home         float64
 80   passes_avg_home           float64
 81   possession_avg_home       float64
 82   red_cards_avg_home        float64
 83   shots_avg_home            float64
 84   shots_on_target_avg_home  float64
 85   tackles_avg_home          float64
 86   touches_avg_home          float64
 87   yellow_cards_avg_home     float64
 88   goals_scored_ft_avg_home  float64
 89   goals_conced_ft_avg_home  float64
 90   sg_match_ft_acum_home     float64
 91   goals_scored_ht_avg_home  float64
 92   goals_conced_ht_avg_home  float64
 93   sg_match_ht_acum_home     float64
 94   performance_acum_home     float64
 95   clearances_avg_away       float64
 96   corners_avg_away          float64
 97   fouls_conceded_avg_away   float64
 98   offsides_avg_away         float64
 99   passes_avg_away           float64
 100  possession_avg_away       float64
 101  red_cards_avg_away        float64
 102  shots_avg_away            float64
 103  shots_on_target_avg_away  float64
 104  tackles_avg_away          float64
 105  touches_avg_away          float64
 106  yellow_cards_avg_away     float64
 107  goals_scored_ft_avg_away  float64
 108  goals_conced_ft_avg_away  float64
 109  sg_match_ft_acum_away     float64
 110  goals_scored_ht_avg_away  float64
 111  goals_conced_ht_avg_away  float64
 112  sg_match_ht_acum_away     float64
 113  performance_acum_away     float64
dtypes: float64(100), int64(7), object(7)
memory usage: 3.5+ MB

In [5]:
epl_data['home'] = epl_data['result_full'].str.split('-').str[0]
epl_data['Away'] = epl_data['result_full'].str.split('-').str[1]
epl_data.head()

,Unnamed: 0,link_match,season,date,home_team,away_team,result_full,result_ht,home_clearances,home_corners,...,yellow_cards_avg_away,goals_scored_ft_avg_away,goals_conced_ft_avg_away,sg_match_ft_acum_away,goals_scored_ht_avg_away,goals_conced_ht_avg_away,sg_match_ht_acum_away,performance_acum_away,home,Away
0,0,https://www.premierleague.com/match/7186,10/11,2010-11-01,Blackpool,West Bromwich Albion,2-1,1-0,15.0,8.0,...,1.6,1.44,1.67,-2.0,0.33,0.78,-4.0,55.6,2,1
1,1,https://www.premierleague.com/match/7404,10/11,2011-04-11,Liverpool,Manchester City,3-0,3-0,16.0,6.0,...,2.0,1.61,0.87,23.0,0.87,0.32,17.0,60.2,3,0
2,2,https://www.premierleague.com/match/7255,10/11,2010-12-13,Manchester United,Arsenal,1-0,1-0,26.0,5.0,...,1.8,2.12,1.12,16.0,0.94,0.38,9.0,66.7,1,0
3,3,https://www.premierleague.com/match/7126,10/11,2010-09-13,Stoke City,Aston Villa,2-1,0-1,26.0,8.0,...,2.0,1.33,2.00,-2.0,1.00,1.00,0.0,66.7,2,1
4,4,https://www.premierleague.com/match/7350,10/11,2011-02-14,Fulham,Chelsea,0-0,0-0,50.0,4.0,...,1.4,1.84,0.88,24.0,0.84,0.48,9.0,58.7,0,0

In [ ]:
epl_data['Winner'] = epl_data[['home', 'Away']].apply(lambda row: "Home" if row['home'] > row['Away'] else "Away" if row['home'] < row['Away'] else "Draw" if row['home'])